# Generated by Django 4.0.4 on 2022-06-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_type', '0001_initial'),
        ('car_info', '0001_initial'),
        ('accounts', '0011_rename_user_customadmin_custom_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('car_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_info.carinfo')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mechanic')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_type.servicetype')),
            ],
        ),
    ]
