# Generated by Django 4.0.4 on 2022-06-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
