# Generated by Django 4.0.4 on 2022-06-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0002_servicerequest_is_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='status',
            new_name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='location',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_lon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mechanic_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mechanic_lon',
            field=models.IntegerField(default=0),
        ),
    ]
