# Generated by Django 4.0.4 on 2022-06-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_rename_user_customadmin_custom_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mechanic')),
            ],
        ),
    ]
