# Generated by Django 4.0.4 on 2022-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneno',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
