# Generated by Django 4.0.4 on 2022-06-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customadmin',
            old_name='user',
            new_name='custom_admin',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='mechanic',
            old_name='user',
            new_name='mechanic',
        ),
        migrations.RenameField(
            model_name='trmanager',
            old_name='user',
            new_name='tr_manager',
        ),
    ]
