# Generated by Django 4.0.4 on 2022-06-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduled_service_request', '0001_initial'),
        ('service_request', '0001_initial'),
        ('accounts', '0011_rename_user_customadmin_custom_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mechanic')),
                ('scheduled_service_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduled_service_request.scheduledservicerequest')),
                ('service_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_request.servicerequest')),
            ],
        ),
    ]
